### PR TITLE
fix: add missing free with Marius AI

### PR DESCRIPTION
**Pull request by AxelF44**
I've added missing free follow to the test with Marius AI

### CODE REVIEW

**Review by Njord201 — DISMISSED** [review]

**Review by Marius-P1 — DISMISSED** [review]
Good for me :ok_hand:

**Review by mathieurobert1 — APPROVED** [review]
Nice, well done !

**Review by Njord201 — APPROVED** [review]

**Review by mathieurobert1 — APPROVED** [review]
GG my boy !

**Review by Marius-P1 — APPROVED** [review]
Great :ok_hand:

**Pull request merged**
