### PR TITLE
Implement the Player actions

### PR DESCRIPTION
**Pull request by Marius-P1**
I've added all the actions of the players and the handling of the responses of the server (with a system of callback function). I also added the AI class that contain the API and the Player class.

:warning: The current chooseAction of the player is for the moment only a radom because the logic isn't write for the moment but that will come next.

### CODE REVIEW

**Review by Njord201 — DISMISSED** [review]

**Review by theophile-jr — DISMISSED** [review]

**Review by Thomaltarix — DISMISSED** [review]
Seems fine for me, maybe you could detail a bit you methods comments when they're big, but it's fine

**Review by mathieurobert1 — DISMISSED** [review]

**Review by AxelF44 — DISMISSED** [review]

**Comment by theophile-jr** [comment]
Please follow branch naming conventions

**Review by theophile-jr — APPROVED** [review]

**Review by Njord201 — APPROVED** [review]

**Review by mathieurobert1 — APPROVED** [review]
Seems good

**Review by Thomaltarix — APPROVED** [review]
Seems fine :+1:

**Review by AxelF44 — APPROVED** [review]

**Pull request merged**
