### PR TITLE
Refactor tests architecture, from spread in subfolders to /…

### PR DESCRIPTION
**Pull request by theophile-jr**
Move the tests from ai server & gui folders to root (/tests/ai /tests/server /tests/gui).

### CODE REVIEW

**Review by Njord201 — CHANGES_REQUESTED** [review]
Wait the PR of @AxelF44

**Review by mathieurobert1 — CHANGES_REQUESTED** [review]
Wait the pr of Axel

**Review by Thomaltarix — DISMISSED** [review]

**Review by Njord201 — CHANGES_REQUESTED** [review]
The PR of @AxelF44 is not yet merged.

**Review by mathieurobert1 — APPROVED** [review]

**Review by Thomaltarix — COMMENTED** [review]
Great :+1:  :pensive:

**Pull request merged**
