### PR TITLE
Feat/implement end screen zappy gui

### PR DESCRIPTION
**Pull request by Thomaltarix**
I added a simple end screen to the GUI.

Here's an example of it:

image

At the moment, the end screen is very simple since i don't have a good picture of the player's model in 2d.

But the end screen can easily be upgraded by modifying the `Gui::HudEnd::Display` Method

> [!Note]
> The window will never close unless the user presses `ESCAPE`

### CODE REVIEW

**Review by mathieurobert1 — CHANGES_REQUESTED** [review]
Please write a message to **close with escape**

**Review by Marius-P1 — APPROVED** [review]
:ok_hand:

**Review by mathieurobert1 — COMMENTED** [review]
Nice I love the Picture in description

**Review by mathieurobert1 — APPROVED** [review]
Nice I love the Picture in description

**Pull request merged**
